### ISSUE TITLE
Troubleshoot migration of DKAN sites

### ISSUE THREAD

**Issue by jfrant** [nditech/dkan-update#1]
@blynchNDI is attempting to migrate dkan sites from the old aegir site (staging.ndi.org) to the new aegir site (aegircluster01@ndi.org) but has run into a few issues and would like some help from @mlutfy.

**Comment by blynchNDI** [comment]
@mlutfy - As Jesper mentioned above, we need your help migrating three old dkan sites to the new Aegir server. Just to give a quick overview, we're trying to move the remaining legacy sites that are still needed off of the old Aegir server to aegircluster01 so that we can shut down the old server for good. After some testing, I seemed to be able to succesfully migrate three of the sites we needed to the new server - puttingelectionstowork.ndi.org and youthguide.ndi.org are on the manualsites4 platform and www.liberianlawmakerswatch.org is on the liberianlawmakers platform. These are all I believe built off of a fairly basic drupal install which probably made them easier to move.

The three remaining sites we have left to move are all on the platform demtoolsdkan20160715c on staging.demcloud.org - openinternet.global, trustaccelerator.org, and www.voteswithoutviolence.org. (Within the next 6 months or so we'll actually probably be getting rid of openinternet.global and making trustaccelerator into a static site, so www.voteswithoutviolence.org is the only one that will remain long-term). These are built on the DKAN platform, though probably fairly out of date at this point. I tried several attempts to migrate them, such as tar-ing the platform and reinstalling it on the new server and migrating the sites, and migrating them to a basic drupal install, but wasn't able to get them to migrate successfully. 

Any help you can provide on getting these sites migrated would be greatly appreciated. Note that we don't anticipate making any more of these types of sites ever again, so the only need is to be able to keep the sites running with current functionality and the ability to apply security updates. Also note that these sites very rarely get any content changes, so there shouldn't be any issue with needing to worry about specific migration times to avoid content mismatches between the pre- and post- migration sites.

**Comment by blynchNDI** [comment]
Just as an update, we just received a message from AWS letting us know that the old server is scheduled for retirement on September 16th. Worst case, there should be ways around this, but this gives a tentative timeline for turning off the server. Let us know Mathieu if that time frame seems doable, or if the level of effort here is high enough that it will be difficult to get done by then.

**Comment by mlutfy** [comment]
Hi Ben, voteswithoutviolence has been migrated (in Aegir-speak, I did not change the DNS). I haven't tested the other sites, but I suspect it was caused by the same issues (modules that were not the same version), and should work now.

Debugging notes:

* Aegir remote-import seems to be failing without a clear error (https://aegircluster01.demcloud.org/hosting/task/15454; "Drush command terminated abnormally due to an unrecoverable error.")
* Ran the task on the command line, with: `drush @hm hosting-task 15454 --debug --force`

Error:

```
Additional uncaught exception thrown while handling exception.
Original Error: Call to undefined function i18n_field_entity_property_callback() in entity_metadata_field_entity_property_info() (l
ine 30 of /var/aegir/platforms/demtools-dkan-20160715c/sites/all/modules/contrib/entity/modules/field.info.inc).

Additional
TYPO3\PharStreamWrapper\Exception: Unexpected file extension in &amp;quot;p
har:///usr/local/bin/drush/commands/core/drupal&amp;quot; in Drupal\Core\Security\PharExtensionInterceptor-&gt;assert() (line 38 of /var/aegir/platforms/demtools-dkan-20160715c/misc/typo3/drupal-security/PharExten
sionInterceptor.php).
```

The `i18n` Drupal module on the aegircluster platform was version `7.x-1.13`. I updated it to `7.x-1.27`, which is what staging0 also runs (latest version).

Also ran into this error, also module version issue:

```
PHP Fatal error:  Declaration of RulesRuleUI::form(&$form, &$form_state, $options = Array) must be compatible with RulesActionContainerUI::form(&$form, &$form_state, $options = Array, $iterator = NULL)
in /var/aegir/platforms/demtools-dkan-20160715c/profiles/dkan/modules/contrib/rules/ui/ui.plugins.inc on line 80
```

I did a quick "diff" of the modules/contrib directory and that seemed like the only difference there, however the dkan install profile directory had a few upgrades as well: imagecache_actions, module_filter, rules, services, etc.

I did an rsync of `profiles/dkan` using the code from staging0, so that it has all the same versions.

**Comment by jfrant** [comment]
@blynchNDI finish migration for next week, @jfrant checking about trust accelerator domain

**Comment by jfrant** [comment]
@blynchNDI  We can drop the domain. Please flatten the site and archive it at trustaccelerator.ndi.org.

**Comment by blynchNDI** [comment]
Thanks to @mlutfy for all his help on this - the full migration is done, and the old server has been officially turned off. The trust accelerator site is now running at trustaccelerator.ndi.org, currently just from the new aegir server - I'll work with Carlos when he gets back on making it fully flattened, as he had already done some work on that, but shouldn't need any further help from Mathieu on this.
